apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: product-service:latest
        ports:
        - containerPort: 5002
        env:
          - name: DATABASE_HOST
            value: "postgres"
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_NAME
            value: "mydb"
          - name: DATABASE_USER
            value: "myuser"
          - name: DATABASE_PASSWORD
            value: "mypassword"

---

#Service Product-service

apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservices
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
      nodePort: 30002
  type: NodePort